### ISSUE TITLE
Generated pdfs are corrupted after first request

### ISSUE THREAD

**Issue by revocengiz** [AdaskoTheBeAsT/WkHtmlToX#2]
Hi, first of all thank you for putting effort to make this project.
When I try sample project WebApiCore
The pdf generated from first request is looking as expected but in the flowing requests every things gets kind the text only
Here is sample html you provide. Look at the how paragraph getting inline.
![image](https://user-images.githubusercontent.com/6932535/105497201-9738cd80-5ccf-11eb-93b6-1ac23004db13.png)

When try complex html it getting worse, here is the sample
![image](https://user-images.githubusercontent.com/6932535/105497498-f7c80a80-5ccf-11eb-8c7c-dd908a731fb7.png)

Do you have any suggestions why this is happening after first request.
Thanks in advance.

Sample html I use

[complexpdf.zip](https://github.com/AdaskoTheBeAsT/WkHtmlToX/files/5856161/complexpdf.zip)

**Comment by AdaskoTheBeAsT** [comment]
I will try to investigate that issue - thanks for sample html it will be easier to reproduce

**Comment by AdaskoTheBeAsT** [comment]
Hi,

I am still working on this.
It seems that conversion can be done only in thread which initialized lib.
Tricky part is that in web apps there is a need to create separate conversion thread and unfortunately use singleton.
Anyway I will change internals significantly for this and provide proper tests

**Comment by AdaskoTheBeAsT** [comment]
Hi @revocengiz 

I have done that - it required lots of rework as it seems lib can be loaded only once and initialized in its working thread.
Soon v5.0.0 should be in nuget - there is api breaking change - please take a look at readme and samples

**Comment by revocengiz** [comment]
Awesome, I did test same sample and it's working as expected now. I appreciate for your work. Thank you. :) 
I'll prepare same benchmark test and share with you.

**Comment by AdaskoTheBeAsT** [comment]
Cool - happy to help :) yes please share benchmarks - I am very interested in that.
I will close that issue.
