### ISSUE TITLE
Please add a direct reference to your nuget package since there are a lot of WkHtmlToX

### ISSUE THREAD

**Issue by arivera12** [AdaskoTheBeAsT/WkHtmlToX#4]

**Comment by AdaskoTheBeAsT** [comment]
Hi,

it is by design - as native libraries are quite large (15MB for win others similar size) 
User of lib is responsible for attaching correspondin package with native lib for platform he use (for win64  https://www.nuget.org/packages/AdaskoTheBeAsT.WkHtmlToX.native.win.x64/)

**Comment by arivera12** [comment]
I saw and read about this but it would be nice having this list on the main docs. Closing.
