### ISSUE TITLE
How to user the html to image converter?

### ISSUE THREAD

**Issue by arivera12** [AdaskoTheBeAsT/WkHtmlToX#5]
I almots had everything set but don't know where to set the html document in the `HtmlToImageDocument`

Which prop I should use to set the html document?

`HtmlToImageDocument.ImageSettings.  ???  = htmlDocumentTemplate;`

**Comment by AdaskoTheBeAsT** [comment]
Hi,

it is property In as described in comment 
https://github.com/AdaskoTheBeAsT/WkHtmlToX/blob/e739335a44fb971e755f35df6112ee0db5fc088b/src/AdaskoTheBeAsT.WkHtmlToX/Settings/ImageSettings.cs#L51

**Comment by arivera12** [comment]
Is there a way to use a stream or byte array instead of  specifying the file from a path?

**Comment by AdaskoTheBeAsT** [comment]
noe unfortunately native lib has only such functionality - in property "In" you can pass url or filename

**Comment by arivera12** [comment]
Ok
